events {}
http {
    upstream samba_backend {
        server samba_ad:80;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://samba_backend;
        }
    }

    server {
        listen 443 ssl;
        ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
        location / {
            proxy_pass http://samba_backend;
        }
    }
}
